from enum import Enum


class EnumSentimentLabel(str, Enum):
    POSITIVE = "POSITIVE"
    NEUTRAL = "NEUTRAL"
    NEGATIVE = "NEGATIVE"
    VERY_POSITIVE = "VERY_POSTIVE"
    VERY_NEGATIVE = "VERY_NEGATIVE"


class EnumWordCloudMeasure(str, Enum):
    FREQUENCY = "FREQUENCY"
    LOG_LIKELIHOOD = "LOG_LIKELIHOOD"
    KEYNESS = "KEYNESS"


class EnumWordCloudType(str, Enum):
    ALL_WORDS = "ALL_WORDS"
    NOUNS = "NOUS"
    PROPER_NOUNS = "PROPER_NOUNS"
    ADJECTIVES = "ADJECTIVES"
    ADVERBS = "ADVERBS"
    NUMBERS = "NUMBERS"
    TWO_WORDS_CLUSTER = "TWO_WORDS_CLUSTER"
    THREE_WORDS_CLUSTER = "THREE_WORDS_CLUSTER"
    FOUR_WORDS_CLUSTER = "FOUR_WORDS_CLUSTER"
    SEMANTIC_TAGS = "SEMANTIC_TAGS"
